// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: New_UI

#ifndef _NEW_UI_UI_H
#define _NEW_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Displaylogo_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
void ui_event_MainPage( lv_event_t * e);
extern lv_obj_t *ui_MainPage;
extern lv_obj_t *ui_logo;
// SCREEN: ui_OpenSwichPage
void ui_OpenSwichPage_screen_init(void);
extern lv_obj_t *ui_OpenSwichPage;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
void ui_event_S1( lv_event_t * e);
extern lv_obj_t *ui_S1;
void ui_event_S3( lv_event_t * e);
extern lv_obj_t *ui_S3;
void ui_event_S2( lv_event_t * e);
extern lv_obj_t *ui_S2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_image_logo_chang_png);   // assets/Image/logo_chang.png
LV_IMG_DECLARE( ui_img_2095349367);   // assets/Image/🦆 icon _bell_.png


LV_FONT_DECLARE( ui_font_Fontbig);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
