// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: New_UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void On_relay220VAC(lv_event_t * e);
void Btb_close(lv_event_t * e);
void Pressd_S1(lv_event_t * e);
void Pressd_S3(lv_event_t * e);
void Pressd_S2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
